# Default values for person-structure.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""

image:
  repository: docker.io/hrvestigo/person-structure-ms
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

datasource:
  host: ""
  port: ""
  dbName: ""
  user: ""
  liquibaseUser: ""
  schema: ""
  connTimeout: 60000
  maxPoolSize: 2
  minIdle: 0

kafka:
  user: ""
  servers: ""
  saslMechanism: PLAIN
  securityProtocol: SASL_SSL
  schemaRegistry:
    credSource: USER_INFO
    user: ""
    url: ""
  topics:
    card:
      name: hr.vestigo.hp.card
      consumerGroup: hr.vestigo.hp.card
    crdintacc:
      name: hr.vestigo.hp.crdintacc
      consumerGroup: hr.vestigo.hp.crdintacc
    custcrdintacc:
      name: hr.vestigo.hp.custcrdintacc
      consumerGroup: hr.vestigo.hp.custcrdintacc
    customeraccount:
      name: hr.vestigo.hp.customeraccount
      consumerGroup: hr.vestigo.hp.customeraccount
    authptragrmtlimalc:
      name: hr.vestigo.hp.authptragrmtlimalc
      consumerGroup: hr.vestigo.hp.authptragrmtlimalc

timezone: ""

secret:
  decryptionKey: ""
  datasourcePassword: ""
  kafkaPassword: ""
  kafkaSchemaRegistryPassword: ""
  liquibasePassword: "" # b64 encoded

logger:
  logToFile: false
  rollingFileAppender: false
  logDir: "/var/log/app"
  logDirMount:
    enabled: false
    # spec:
      # emptyDir: {}
      # flexVolume:
        # driver: ""
        # fsType: ""
        # options:
          # basepath: ""
          # basename: ""

healthStatusDownReturnCode: "418"

javaOpts: "-Xms256M -Xmx256M"

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

securityContext: {}

service:
  type: ClusterIP
  port: 8443

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi

initContainers: []

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - person-structure
          topologyKey: kubernetes.io/hostname

deployment:
  replicaCount: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 60
  terminationGracePeriodSeconds: 60
  restartPolicy: Always
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 181
    successThreshold: 1
    failureThreshold: 2
    httpGet:
      path: /health/readiness
      port: http
      scheme: HTTPS
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 60
    timeoutSeconds: 10
    failureThreshold: 3
    httpGet:
      path: /health/liveness
      port: http
      scheme: HTTPS

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

mountServerCertFromSecret:
  enabled: false
  secretName: ""
  certPath: ""
  keyPath: ""

mountKeyStoreFromSecret:
  enabled: false
  secretName: ""
  location: ""
  keyStoreName: ""
  keyStoreType: JKS

mountTrustStoreFromSecret:
  enabled: false
  secretName: ""
  location: ""
  trustStoreName: ""
  trustStoreType: JKS

customVolumes: []

customMounts: []

customEnv: []
